name: Keep Render Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run keep-alive bot
        run: |
          pip install requests
          python bot.py
